baseURL = '/'
languageCode = 'en-us'
title = 'Raisso'

[params]
 
[[params.socail]]
url = "/"
icon = "fab fa-facebook-f"
[[params.socail]]
url = "/"
icon = "fab fa-twitter"

[[params.socail]]
url = "/"
icon = "fab fa-linkedin-in"

[[params.socail]]
url = "/"
icon = "fab fa-google-plus-g"

[[params.socail]]
url = "/"
icon = "fab fa-instagram"

 

    

[minify.tdewolff.html]
keepWhitespace = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
